on:
  push:
    branches: [ "main", "master" ]
    paths-ignore:
      - ".github/workflows/**"   # editing workflows won't trigger app
      - "mysql/**"               # keep MySQL independent
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - ".github/workflows/**"
      - "mysql/**"
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

