name: Build and push to ECR

on:
  push:
    branches: [ main ]  # your default branch is main

permissions:
  contents: read
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      WEB_URI: ${{ secrets.ECR_WEB_URI }}
      MYSQL_URI: ${{ secrets.ECR_MYSQL_URI }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & push webapp
        working-directory: templates
        run: |
          docker build -t ${WEB_URI}:latest -f Dockerfile .
          docker push ${WEB_URI}:latest

      - name: Push mysql (official image re-tag)
        run: |
          docker pull mysql:8.0
          docker tag mysql:8.0 ${MYSQL_URI}:latest
          docker push ${MYSQL_URI}:latest
