name: Build & Push App to ECR

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & push webapp
        env:
          WEBAPP_URI: ${{ secrets.ECR_WEBAPP_URI }}
        run: |
          docker build -f Dockerfile -t "$WEBAPP_URI:latest" .
          docker push "$WEBAPP_URI:latest"

      - name: Build & push mysql
        env:
          MYSQL_URI: ${{ secrets.ECR_MYSQL_URI }}
        run: |
          docker build -f Dockerfile_mysql -t "$MYSQL_URI:latest" .
          docker push "$MYSQL_URI:latest"
