name: Diagnose AWS/ECR
on:
  workflow_dispatch: {}      # ONLY manual runs
# (no 'push:' here)
jobs:
  diag:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ vars.AWS_REGION }}
      - run: aws sts get-caller-identity
      - run: aws ecr get-authorization-token --output json >/dev/null

