name: smoke
on: [workflow_dispatch]

jobs:
  ping:
    runs-on: [self-hosted, linux, x64]
    defaults:
      run:
        shell: bash
    steps:
      - name: Sanity
        run: |
          echo "Runner: $HOSTNAME"
          uname -a
          df -h /
